version: '3'

services:  
  client:
    build: 
      context: ./fe-user
      dockerfile: Dockerfile
    container_name: client      
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./fe-user:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    depends_on:
       - api

  # api:
  #   build: 
  #     context: ./be-user
  #     dockerfile: Dockerfile
  #   container_name: api
  #   working_dir: /usr/src/app
  #   networks: 
  #     - node-network
  #   volumes: 
  #     - ./be-user:/usr/src/app
  #     - /usr/src/app/node_modules
    
  #   command: npm start
  #   depends_on:
  #      - db
  api:
    build: 
      context: ./be-user-new
      dockerfile: Dockerfile
    container_name: api
    working_dir: /usr/src/app
    networks: 
      - node-network
    volumes: 
      - ./be-user:/usr/src/app
      - /usr/src/app/node_modules
    
    command: npm start
    depends_on:
       - db

  db:
    image: mongo
    container_name: db
    restart: always
    tty: true
    ports: 
      - "27017:27017"
    networks: 
      - node-network    

  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    networks: 
      - node-network
    depends_on:
       - api
       - client     
  
  
networks: 
  node-network:
    driver: bridge  
